### ISSUE TITLE
Reverse wrong commit

### ISSUE THREAD

**Issue by ReturnEnd** [Gabyfle/gName-Changer#11]
Can you please reverse this commit, Makss and I explained why it's useless and counter productive.
https://github.com/Gabyfle/gName-Changer/commit/57969c7955d676bbaf4d836ed4db508d8b5b825e

Side note : Users aren't able to assign labels on issues.

**Comment by Gabyfle** [comment]
That's solved, the https://github.com/Gabyfle/gName-Changer/commit/57969c7955d676bbaf4d836ed4db508d8b5b825e commit has been reverted.

Sorry for the trouble.
