### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AlexNova1555** [Gabyfle/gName-Changer#12]
getting this error after first install

```
[ERROR] addons/gname-changer/lua/gnamechanger/sh_gnamechanger.lua:92: attempt to call method 'getDarkRPVar' (a nil value)
  1. LangMatch - addons/gname-changer/lua/gnamechanger/sh_gnamechanger.lua:92
   2. func - addons/gname-changer/lua/gnamechanger/name_system/firstspawn/cl_firstspawn.lua:121
    3. unknown - lua/includes/extensions/net.lua:32
```

**Comment by Gabyfle** [comment]
Hello @AlexNova1555 !
Thanks for using **gNameChanger**!

I took note of your problem, and I **couldn't** reproduce it. Is it possible to get a full log of your server (to know how to get it, go here: [tutorial](https://www.gmodstore.com/community/threads/2682)).
Nevertheless, I have my own idea of where your problem comes from.

Are you sure that **DarkRP** is **properly installed** on your server ?

Thank you in advance,
Gabyfle

**Comment by AlexNova1555** [comment]
Here is the Full server log:
https://pastebin.com/mgyjaEJ3

and yes i have installed darkrp properly and using 2.7.0 version

**Comment by Gabyfle** [comment]
Okay, thanks for reporting this issue, I'll do my investigations.

I try to fix it as soon as possible, sorry for the inconvenience.
Gabyfle.

**Comment by Gabyfle** [comment]
After trying to reproduce your mistake, I **couldn't** do it.
I still changed the way I get the player's name, I hope it will fix your problem.

Let me know if the error appears again.

Yours sincerely,
@Gabyfle.

**Comment by Gabyfle** [comment]
Ok, that's quite embarrassing, I don't have mich time to fix it now, but this afternoon I'll work on it.

Sorry for the inconvenience,
Gabyfle.

**Comment by Gabyfle** [comment]
I made a slight update, after some research, I think I found out where the problem comes from. Try the new update and **let me know** if your problem persists.



PS : _the closure of this issue was not voluntary, sorry for the unnecessary notifications 🥇_

**Comment by AlexNova1555** [comment]
good new: it is now working!
thanks for your help!!

but one small problem, players can still use the command "/nick" to change thier names for free
can u fix it too?

**Comment by Gabyfle** [comment]
Hey @AlexNova1555,
Thanks for reporting me this Issue, I fix it in few seconds.

**Comment by Gabyfle** [comment]
Normally, everything must be correct now. I await your answer to close this Issue.

Thanks a lot,
Gabyfle.

**Comment by AlexNova1555** [comment]
Everything is now working!
thanks for your great support, loving this addon and easy to use!

Have a nice day.
you can now close the ticket.

- Alex.

**Comment by Gabyfle** [comment]
I am happy that you like my creation, don't hesitate to talk about it around you,
Gabyfle.

**Comment by AlexNova1555** [comment]
i got an new problem /=
after choosing and then quit or restart the server it says to me to choose a name again.

**Comment by Gabyfle** [comment]
Hey!

I know that Issue, I'll be working on it next week, I hope it isn't too embarrassing for you.

Sorry for the inconvenience,
Gabyfle.

**Comment by AlexNova1555** [comment]
sure thing i will be waiting!

thanks for your help

**Comment by AlexNova1555** [comment]
oh and last thing, can you please add an notification when you changed your name with the npc please?

**Comment by Gabyfle** [comment]
There is already a notification about that.
