### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Pichwise** [Gabyfle/gName-Changer#15]
Hello, everytime I spawn in, it ask me to change my name. Would it be possible to make it ask only once?
Also the admins commands are not working on my side even when my rank is in the list allowed to use commands.

Thanks!

**Comment by Gabyfle** [comment]
Hello @Pichwise,

I'm currently **working** on a fix to stop ask to change the name on every new connection.
The ranks aren't based on ULX or other admin manager tool, I'll try to improve this system.

Thanks for contributing to **gNameChanger**,
Gabyfle

**Comment by Gabyfle** [comment]
Hello, it's again me @Pichwise,

I've tried to replicate your Issue, but after many tries, I cannot find the source of the problem.
I don't even know which rank system are you using in your server, but it have to return your rank with the **[GetUserGroup()](https://wiki.garrysmod.com/page/Player/GetUserGroup)** function.

If you are working with **ULX**, try to change your group, and check if you don't make a mistake while copying it into your config file.

I hope this can help you,
Gabyfle.

**Comment by Gabyfle** [comment]
Hello @Pichwise,

I haven't experienced any problems concerning this feature, so I'll try to do my best to help you. First, can you send me your **gNameChanger** config file, and a screenshot of your ULX Groups ?

I've just fixed the "name change bug", try the new version and don't forget to let me know if there is any bug :)

Thanks a lot,
Gabyfle.

**Comment by Gabyfle** [comment]
No new answer since 4 months, closing.
