### ISSUE TITLE
gNameChanger problem

### ISSUE THREAD

**Issue by DarkScientist** [Gabyfle/gName-Changer#16]
Hello, very nice, clean and good addon!

But I've got a problem...
When I connect, it asks me every time to change my name, that is not useful. 

Thanks 

DarkScientist_

**Comment by Gabyfle** [comment]
Hi @DarkScientist,
I will push a new update this Friday, no worries about this problem ;)

Thanks,
Gabyfle

**Comment by DarkScientist** [comment]
Hello,
What about this problem? 

Thanks

**Comment by Gabyfle** [comment]
Hey @DarkScientist,
I'm pretty dumb, I've forgot to push the new update...
Everything is ready, I have to wait this week-end because I don't have access to my computer right now, sorry for the inconvenience.

Sorry,
Gabyfle.

**Comment by Gabyfle** [comment]
Hey, it's again me @DarkScientist !

The bug should now be fixed, try yourself the new version and let me know if you experience any other bug !

Thanks you for contributing to **gNameChanger**,
Gabyfle.

**Comment by DarkScientist** [comment]
Hey, sorry for the very late response. 
Yes it's fixed! Thanks! 

Have a good day!
