### ISSUE TITLE
a way to bypass the name menu

### ISSUE THREAD

**Issue by AlexNova1555** [Gabyfle/gName-Changer#17]
so if a new player joins the server and then leaves without setup his name and then comes back to the server he wont see the name menu GUI /=

**Comment by Gabyfle** [comment]
Hello @AlexNova1555,
I will fix this issue this afternoon, sorry for the inconvenience.

Thanks,
Gabyfle

**Comment by Gabyfle** [comment]
Hello again @AlexNova1555,

I've pushed a new update concerning this bypass. Let me know if it isn't working well, and if you experience any bug.

Thanks for your contribution to **gNameChanger**,
Gabyfle.

**Comment by AlexNova1555** [comment]
@Gabyfle yap that did the trick :D
working find now!

but i got new problem
how can i block so player can put spaces in thier names?
because if player just press space and press enter so he doesn't have a name.
