### ISSUE TITLE
terrible translation + just get the currency from the darkrp

### ISSUE THREAD

**Issue by ExtReMLapin** [Gabyfle/gName-Changer#19]
https://github.com/Gabyfle/gName-Changer/blob/dc3a2c423b7a8ccd1ba84432ccf5219d14a7f036/gname-changer/lua/autorun/gname_changer_config.lua#L53

terrible english, also, just get the currency from the darkrp

**Comment by Gabyfle** [comment]
Do you prefer "currency" ?
And yeah, I hadn't thought of it. I'll push a commit in the next hours. Thanks !

**Comment by Gabyfle** [comment]
I think it must be good. The currency is now managed by DarkRP, as you suggested.
