### ISSUE TITLE
Name Change at spawn is infinte

### ISSUE THREAD

**Issue by Stig124** [Gabyfle/gName-Changer#21]
On last version, on spawn when I enter the name and click on the enter button the menu come on and on indefinitly
- Last GMOD/DarkRP version

**Comment by Gabyfle** [comment]
Hi,
Have you any informations on how I can reproduce this error ?

Gabyfle.

**Comment by Stig124** [comment]
I installed the addon and at the time I rebooted for getting the addons working I entered a name and entered, the name is correctly changed but the menu reset and stay on top

**Comment by Gabyfle** [comment]
Can you please post your config file here ? (in code tags ` `` `)

I tried to reproduce it, but but I missed it.

Gabyfle.

**Comment by Stig124** [comment]
The config is the initial config because the bug appear on the first launch without any config modification

**Comment by Gabyfle** [comment]
I'm investigating. I'll try to fix this issue as soon as possible. Thanks for reporting it and sorry for the inconvenient.

**Comment by Gabyfle** [comment]
@Stig124 can you give me your server's IP ? I'll check some things to see what happens.
I cannot find a way to reproduce your problem on my local-hosted server.

**Comment by Stig124** [comment]
The bug is solved on last update

**Comment by Gabyfle** [comment]
Thanks. Closed.

**Comment by sword134** [comment]
@Gabyfle i've got this exact error now. Latest version just out of the box installation no config changes
