### ISSUE TITLE
Ajout de fonctionnalité

### ISSUE THREAD

**Issue by NoaGamingFR** [Gabyfle/gName-Changer#9]
Nice, ca avance tout sa, ca fait plaiz.
Parcontre, une petite question.

Est-ce que le changement de nom rp à l'arrivée est-il obligatoire ?
Si non, pourrais-tu l'ajouter et permettre de le désactiver dans les config, pour ceux qui n'en veulent pas ?
Merci :)

**Comment by Gabyfle** [comment]
Hi @NoaGamingFR 

Thanks for taking an interest in the project, it's good to see you. This feature is planned in the next updates, I will close this Issue when it's done.

Yours very much,
Gabyfle.

**Comment by Gabyfle** [comment]
This feature is now included in **gNameChanger**.
Thank you for sharing it with us.
